### ISSUE TITLE
Guide for AwesomeWM Development Environment

### ISSUE THREAD

**Issue by raven2cz** [awesomeWM/awesome-www#161]
### AwesomeWM DevEnv

Basic user configurations, simple wibars, layouts, basic themes don't need libs import and looking to the libraries of AW project. It is possible to use with the AW API and its documentation.

However, this will quickly change if you need to start doing more complex things and components. When using Lua components, it is often necessary to look at implementations and cooperation already written in the AW library.

Furthermore, there may be a large group of people who can begin to contribute to AW fixes and enhancements; so that stable versions have a shorter release cycle again.

I don't think I'll be alone who lacks simple tutorials on how to run a "quality" environment for AW development; source code and AW debugging are available throughout the project, as used by contributors to this project.

Furthermore, I think that this will also help to unify the use of some of the **tools** that are needed for this.

So is it possible for experienced contributors to create a quality guide for setting up a development environment to contribute to a project and include it on the main AW pages? This can open the door to the points which are already described.

**Comment by actionless** [comment]
I think the part with the guide itself actually also belongs to awesome-www, so i moved it all here

**Comment by actionless** [comment]
i recommends re-opening a new ticket for the remaining items (and if possible split to smaller tasks, and create accordingly in awesomeWM repo if it's smth to improve in the docs, or here if smth still left regarding improving website itself)
