### ISSUE TITLE
Authors/contributors are not aligned properly

### ISSUE THREAD

**Issue by blueyed** [awesomeWM/awesome-www#18]
Probably caused by some bug with `column` etc on the Ubuntu version being used on Travis.

Ref: https://github.com/awesomeWM/awesome-www/pull/11#issuecomment-219468880

**Comment by Elv13** [comment]
This bug has been "fixed" by the removal that list. We now have https://github.com/awesomeWM/awesome/graphs and https://awesomewm.org/apidoc/documentation/00-authors.md.html,
