### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by Sathors** [awesomeWM/awesome-www#23]
Right now, the website seems to be down.

Cloudflare offers some backup access, but some pages of the wiki do not work altogether.

**Comment by blueyed** [comment]
Oh.. http://www.awesomewm.org/ should not really go through CloudFlare.

@jd @psychon 
Have you changed some DNS settings?!

**Comment by blueyed** [comment]
http://new.awesomewm.org/ works - which should become the new website once the wiki is transferred etc.

**Comment by psychon** [comment]
I didn't touch anything (and I don't think I even could touch anything, do I have access rights for anything?). If @jd doesn't report back, I guess it's time to remove the wiki and the old issue tracker from the new version of the website and start using that one instead?

**Comment by jd** [comment]
There was a configuration issue on the server (a letsencrypt renewal failed) and it went down for a few hours. I fixed that.

Yes, it's gonna be time to move this elsewhere. Server is still planned to definitely go down 31st December 2016.
