### ISSUE TITLE
Can't get access to Wiki pages

### ISSUE THREAD

**Issue by andrey-str** [awesomeWM/awesome-www#33]
Link to wiki(https://awesomewm.org/wiki/) shows me this:

![1482172647](https://cloud.githubusercontent.com/assets/1244405/21324689/468177a8-c63c-11e6-8c56-4be30d5f4c66.png)

Is this something wrong on my end? Was working fine few days ago.

**Comment by Elv13** [comment]
Hello,

We retired the old wiki a few days ago. We may, or may not, add a static copy at some point. The new documentation is available at https://awesomewm.org/apidoc/ . If you think it is missing important information, please say so, we will add it back.

The old wiki was almost dead, most of the content was outdated and we had spam issues that forced us to disable new accounts for a long time. Also, 4.0 is about to be released and will cause even more content to be outdated, so now is a good time to switch to the new system. Also note people who wish to add content can do it from GitHub and submit a pull request. This will solve the spam problem.

**Comment by blueyed** [comment]
@andrey-str 
Where do you got the old link from? (we might want to update that)

@Elv13 
Should we have a redirect from `/wiki` to `/apidoc`?

**Comment by blueyed** [comment]
We could also have a custom 404 page: https://help.github.com/articles/creating-a-custom-404-page-for-your-github-pages-site/.

**Comment by Elv13** [comment]
> @Elv13 Should we have a redirect from /wiki to /apidoc?

Yes, it makes sense.

> We could also have a custom 404 page: https://help.github.com/articles/creating-a-custom-404-page-for-your-github-pages-site/.

Sure, but the redirect is both easier to implement and, in this case, much more useful.

**Comment by blueyed** [comment]
Ok, done.
