### ISSUE TITLE
https certificate has been expired

### ISSUE THREAD

**Issue by xatier** [awesomeWM/awesome-www#4]
The certificate has been expired on March 7th. Please update.

![img](https://i.imgur.com/22kYjql.png)

**Comment by psychon** [comment]
@jd ping

**Comment by jd** [comment]
Yup, on my TODO list!

**Comment by blueyed** [comment]
@jd 
Via https://letsencrypt.org/ ?

**Comment by jd** [comment]
@blueyed that's the plan :)

**Comment by jd** [comment]
Should be OK for a year!

**Comment by xatier** [comment]
What about this domain?

https://awesomewm.org/

**Comment by psychon** [comment]
@blueyed Hey, since when do we have awesomewm.org? I didn't know, but the whois entry "blames" you. Since apparently the certificate was valid for it before as well, apparently jd knows about this and set it up...?

**Comment by xatier** [comment]
Not sure about the details either, but it seems be on the repo description of the main repo for a while.

https://github.com/awesomeWM/awesome

**Comment by jd** [comment]
Right, it's an alias.

I've upgraded the conf to always redirect to https, and requested a SSL certificate for awesomewm.org.

(at this pace i'm gonna be a SSL consultant pretty soon)
