### ISSUE TITLE
Travis: remove branches.only: master / check TRAVIS_BRANCH in build instead

### ISSUE THREAD

**Issue by blueyed** [awesomeWM/awesome-www#42]
Via https://github.com/awesomeWM/awesome-www/pull/37#issue-197456783

> `branches.only: master` in .travis.yml…
> Can we remove that setting and instead use some `if` with `$TRAVIS_BRANCH` to make sure only non-PR builds for the master branch update the web page?

**Comment by actionless** [comment]
if that's still a thing?

**Comment by Elv13** [comment]
No, it's not
