### ISSUE TITLE
Image (382x216-screen.png) changes constantly

### ISSUE THREAD

**Issue by blueyed** [awesomeWM/awesome-www#46]
Via https://github.com/awesomeWM/awesomeWM.github.io/commit/dc92eee8de839690ccb2778bf74bc48b08cbac31#commitcomment-20293357:

It turns out that the footer of the image changes:

Via `diff -u =(git show c646eb972d:index/382x216-screen.png | hexdump -C) =(git show c646eb972d~1:index/382x216-screen.png | hexdump -C)`:

```diff
--- /tmp/zshyQ69o4	2016-12-25 23:29:12.822000142 +0100
+++ /tmp/zshMuqqOv	2016-12-25 23:29:12.842000400 +0100
@@ -4988,9 +4988,9 @@
 000137b0  12 c6 08 17 94 d1 ff 17  a1 9b 74 be e4 47 27 ce  |..........t..G'.|
 000137c0  00 00 00 25 74 45 58 74  64 61 74 65 3a 63 72 65  |...%tEXtdate:cre|
 000137d0  61 74 65 00 32 30 31 36  2d 31 32 2d 32 35 54 32  |ate.2016-12-25T2|
-000137e0  32 3a 31 30 3a 32 35 2b  30 30 3a 30 30 e7 9f f3  |2:10:25+00:00...|
-000137f0  d5 00 00 00 25 74 45 58  74 64 61 74 65 3a 6d 6f  |....%tEXtdate:mo|
+000137e0  31 3a 34 32 3a 32 36 2b  30 30 3a 30 30 1e 1f f9  |1:42:26+00:00...|
+000137f0  f9 00 00 00 25 74 45 58  74 64 61 74 65 3a 6d 6f  |....%tEXtdate:mo|
 00013800  64 69 66 79 00 32 30 31  36 2d 31 32 2d 32 35 54  |dify.2016-12-25T|
-00013810  32 32 3a 31 30 3a 32 35  2b 30 30 3a 30 30 96 c2  |22:10:25+00:00..|
-00013820  4b 69 00 00 00 00 49 45  4e 44 ae 42 60 82        |Ki....IEND.B`.|
+00013810  32 31 3a 34 32 3a 32 36  2b 30 30 3a 30 30 6f 42  |21:42:26+00:00oB|
+00013820  41 45 00 00 00 00 49 45  4e 44 ae 42 60 82        |AE....IEND.B`.|
 0001382e
```

**Comment by psychon** [comment]
Fun fact: The old image is still laying around in there: https://github.com/awesomeWM/awesomeWM.github.io/tree/master/index
#50 should deal with that.

Another fun fact: I cannot reproduce this locally. I guess something important changed between Trusty's ikiwiki 3.20130904 and my local 3.20160905.

So... I'll continue to ignore this issue, sorry.

**Comment by actionless** [comment]
https://github.com/awesomeWM/awesomeWM.github.io/commit/87994acfceb149e120027042ec1d5164d1c17ed5

1) the picture in question was removed
2) original picture (not resized) not causing such issue
