### ISSUE TITLE
Use English version paypal

### ISSUE THREAD

**Issue by xatier** [awesomeWM/awesome-www#5]
Please consider using English version Paypal for the donation information page. It looks like French(?) currently.

**Comment by Elv13** [comment]
The French link is no longer there.

**Comment by blueyed** [comment]
@Elv13 
Still there: https://github.com/awesomeWM/awesome-www/blob/09398c808b72ee22dc5e46f5be9cfe0e0ddf5bb5/templates/page.tmpl#L120
