### ISSUE TITLE
Changelog content-type is not set

### ISSUE THREAD

**Issue by jd** [awesomeWM/awesome-www#51]
When clicking links such as:
https://awesomewm.org//changelogs/v4.0

the content type is unset, so the browser downloads it. It should be renamed with an extension such as `.txt` or the server should send the proper `Content-Type` header.

**Comment by blueyed** [comment]
According to https://help.github.com/articles/mime-types-on-github-pages/ it does not look like you can change this without changing the filename.

**Comment by blueyed** [comment]
btw: check out https://github.com/spasche/openinbrowser.
