### ISSUE TITLE
Use valid HTML and CSS

### ISSUE THREAD

**Issue by psychon** [awesomeWM/awesome-www#60]
https://validator.w3.org/check?uri=http%3A%2F%2Fawesomewm.org&charset=%28detect+automatically%29&doctype=Inline&group=0

https://jigsaw.w3.org/css-validator/validator?uri=http%3A%2F%2Fawesomewm.org&profile=css3&usermedium=all&warning=1&vextwarning=&lang=en

(but not only the main page should be checked, but also sub pages)

**Comment by blueyed** [comment]
We should probably use a more modern validator, like https://validator.nu/?doc=https%3A%2F%2Fawesomewm.org (still errors there though).

**Comment by aajjbb** [comment]
As @blueyed fixed CSS issues and me the HTML ones, this issue can be closed, right ?

**Comment by blueyed** [comment]
💥

**Comment by psychon** [comment]
Thank you!
