### ISSUE TITLE
Do we really need 2 doc tabs ?

### ISSUE THREAD

**Issue by aajjbb** [awesomeWM/awesome-www#64]
The site currently has 2 doc tabs (v4.0 and git/master), but this information is already contained one tab (v4.0). Wouldn't be wiser to keep one single doc tab with all documentation information.

Also, the current URL suffix for the stable branch docs is called `doc/api`, isn't it better to rename it to something related to that specific stable version (like `/api/v4.0`) for example.

**Comment by blueyed** [comment]
We should only have https://awesomewm.org/doc/ as "doc".
This includes a link to apidoc (master doc) already.

**Comment by blueyed** [comment]
> Also, the current URL suffix for the stable branch docs is called doc/api, isn't it better to rename it to something related to that specific stable version (like /api/v4.0) for example.

Yes, we should include the version in the docs we are building, and then have a `api` symlink to the current one.

**Comment by blueyed** [comment]
The 2nd issue is more complex, so I've created https://github.com/awesomeWM/awesome-www/issues/67.
