### ISSUE TITLE
generated HTML in the docs is sometimes falsely escaped

### ISSUE THREAD

**Issue by mqus** [awesomeWM/awesome-www#68]
Hi! 
While rewriting my rc.lua to awesome4(thank you for the nice work btw ;-) ) i noticed some 'over-escaped' statements in the examples section of https://awesomewm.org/apidoc/classes/wibox.widget.progressbar.html# that shouldn't be there 
example:
<pre>value         = &lt;span class="number"&gt;0.33&lt;/span&gt; </pre>
should be:
<pre>value         = 0.33</pre>

**Comment by blueyed** [comment]
Thanks for the report!

@Elv13 
Do you want to pick this up (just a guess about the issue coming through your changes though!)

@mqus 
Feel free to try fixing it yourself in the `aweesome` repo.. :)

**Comment by psychon** [comment]
Uhm. The question is: Why is the doc wrong? I have the correct docs locally. Does Ubuntu Ancient have a version of markdown-something with a different behaviour?

Oh and: I think this span tag is added by LDoc/markdown/something-else and not by us...?

**Comment by blueyed** [comment]
Maybe related to having `lua-discount` installed or not?!
Also there are different `markdown` implementations being considered by `ldoc` itself.
FWIW: it looks good locally for me, too.

**Comment by psychon** [comment]
I have lua-discount 2.1.8-2 (debian testing) installed. I do not have lua-markdown installed. Those are the two optional dependencies of lua-ldoc here.
Travis uses lua-discount 1.2.10.1-1. https://travis-ci.org/awesomeWM/awesome/jobs/194257428#L2127 and markdown-0.33-1 https://travis-ci.org/awesomeWM/awesome/jobs/194257428#L1883 (???).

**Comment by blueyed** [comment]
Maybe https://github.com/awesomeWM/awesome/pull/1428 fixes it?!

**Comment by blueyed** [comment]
Tried the forceful removal of `markdown` in there, but did not change anything: https://github.com/awesomeWM/apidoc/compare/7fca69d...ac0e4d6#diff-53d596669c052ae5438516a7fecaf67d (https://github.com/awesomeWM/apidoc/blob/ac0e4d687f0250749eb05edabfbdece7b2d2e955/classes/wibox.widget.progressbar.html#L193).

**Comment by Elv13** [comment]
https://awesomewm.org/apidoc/documentation/06-appearance.md.html
https://awesomewm.org/doc/api/documentation/06-appearance.md.html

Are different, `apidoc` is correct, `doc/api` is wrong

**Comment by blueyed** [comment]
Then the wrong one is caused by https://github.com/awesomeWM/awesome-www/blob/master/.travis.yml.
Or it is fixed by now, but we're building the v4 tag there still..?!

**Comment by blueyed** [comment]
I've build v4.0 locally, and it is also correct (i.e. `arcchart_border_color` and not `arcchartbordercolor` like on /doc/api..

**Comment by mqus** [comment]
as this seems to be solved (Thank you!), I'll close the issue
