### ISSUE TITLE
[urgent] Add a link to the NEWS and porting guide on the homepage

### ISSUE THREAD

**Issue by Elv13** [awesomeWM/awesome-www#69]
Arch, Debian Sid and Ubuntu zenial all pushed 4.0, breaking everybody's config. We've been there before, but it has been a looong time. We need a temporary message on the homepage (very visible) pointing the users in the right direction:

https://awesomewm.org/apidoc/documentation/89-NEWS.md.html
https://awesomewm.org/apidoc/documentation/17-porting-tips.md.html

**Comment by blueyed** [comment]
What about adding them to the "doc" section?
https://awesomewm.org/doc/

It can also be on the homepage already, but then linking to the doc section?

**Comment by Elv13** [comment]
Not visible enough, the users are already frustrated by the time they hit the website, this will last a couple of weeks. Than a couple more weeks in April (Ubuntu) and later for Fedora.

**Comment by blueyed** [comment]
> Not visible enough

What?
I think it can be on the homepage (in a new NEWS section, just below the first paragraph/section), but the links should be gathered in the "doc" section.
