### ISSUE TITLE
Need to find a new hosting service for mailing list

### ISSUE THREAD

**Issue by jd** [awesomeWM/awesome-www#8]
As the server is going away, it's unlikely the mailing list hosted `awesome@naquadah.org` still stay longer too. I can provide the list of subscriber and even a mail alias, but it should probably go be hosted elsewhere. I've no idea where we can find such a service, but it should be possible. (Freedesktop.org maybe?)

**Deadline is 31st December 2016.**

**Comment by psychon** [comment]
How bad would it be if the mailing list would just go away? I only use it for release announcements, I think.
(Which reminds me: I have to save the old releases from the web server before it is shut down, they aren't in git currently.)

**Comment by jd** [comment]
Considering the regular subscriber decrease trend of the last months and the low traffic, it would probably not be a big problem.

![awesome sub stats](http://mon.naquadah.org/naquadah.org/prometheus.naquadah.org/eoc_subscribers_count_awesome_naquadah_org-year.png)

**Comment by psychon** [comment]
If no one really, really wants the mailing list to stay, I would suggest that you write some "closing down" announcement to the mailing list pointing people to use github instead and then turn it off a while later.

CC'ing random people @Elv13 @blueyed @actionless

(That "subscriber decrease" is, by the way, partly a lie. From a peak of 892 to minimum 846 is just a 5% difference. Still, the mailing list isn't really used much, only @Elv13 answers questions there.)

**Comment by actionless** [comment]
you could mention in a closing announce what interested people could subscribe via RSS:
https://github.com/awesomeWM/awesome/releases.atom

**Comment by blueyed** [comment]
I agree that we should just skip the ML for now.

https://github.com/awesomeWM/awesome/releases.atom is good to mention, but more importantly it should refer to IRC and the GitHub issues for normal users.

**Comment by majutsushi** [comment]
There are also various services that offer free mailing list functionality like http://librelist.com/ and http://www.freelists.org/.

**Comment by actionless** [comment]
it seems like the official website is mentioning mailing list as permanently closed, and there are no any signs of interest from the community for it to re-open
