### ISSUE TITLE
We cannot build the web page currently

### ISSUE THREAD

**Issue by psychon** [awesomeWM/awesome-www#89]
I noticed that https://travis-ci.org/awesomeWM/awesome-www/builds/217685669 failed and wondered why. The difference seems to be penlight 1.4.1 vs penlight 1.5.0. The issue seems to be tracked at https://github.com/stevedonovan/Penlight/issues/243.
If needed, we could pin penlight 1.4.1 for the time being. However, I hope that upstream will fix this and do an update soonish.

**Comment by psychon** [comment]
https://github.com/stevedonovan/Penlight/issues/228#issuecomment-290996120 talks about a 1.5.1 coming soon-ish

**Comment by blueyed** [comment]
Strange: master was never broken?!
I assumed it to be fixed (and somebody had restarted the build for master).

**Comment by psychon** [comment]
Our latest successful build used Penlight 1.5.1. However, that's only available on Luarocks, but not at https://github.com/stevedonovan/Penlight/releases. On the other hand, https://github.com/stevedonovan/Penlight/commit/3f8aaa8a5709145eb61bce9d8dffdef026922dfe bumps the version number from 1.5.0 to 1.5.2. No idea what is going on here. @stevedonovan ???

Closing this since it seems to be fixed.

**Comment by psychon** [comment]
> Strange: master was never broken?!

I think there was no build of master in the time where the latest Penlight release caused issues, that's why.

**Comment by stevedonovan** [comment]
Sanity is restored, 1.5.2 is the new luarocks version. All the zip files are available in https://stevedonovan.github.com/files
