### ISSUE TITLE
Old wiki pages about volume control widgets

### ISSUE THREAD

**Issue by stevenroose** [awesomeWM/awesome-www#99]
I found this answer on SE and the two widgets mentioned there look quite interesting. It might be worth considering putting them in the recipes page. 

I can't find the original content.

https://askubuntu.com/questions/359988/how-to-have-a-volume-control-widget-in-awesome-wm

**Comment by psychon** [comment]
> I can't find the original content.

http://awesome.naquadah.org/wiki/Volume_control_and_display  -> https://awesomewm.org/awesome-www-backup-old/wiki/Volume_control_and_display.html

http://awesome.naquadah.org/wiki/Farhavens_volume_widget -> https://awesomewm.org/awesome-www-backup-old/wiki/Farhavens_volume_widget.html

The linked to images can be found here: https://github.com/awesomeWM/awesome-www-backup-old/tree/gh-pages/w/images (for example https://github.com/awesomeWM/awesome-www-backup-old/blob/gh-pages/w/images/Volume.png)

> It might be worth considering putting them in the recipes page.

Do you want to do that? Pull requests are welcome!

**Comment by aajjbb** [comment]
It's good to see interest in it. After fixing the issues psychon mentioned, feel free to create a pull request with an entry to the recipes section of the site. [More info here](https://github.com/awesomeWM/awesome-www#contributing-to-recipes-section).
